mkjwebsite/blogs/urls.py
from django.urls import path, re_path, reverse
from . import views

app_name = 'blogs'

urlpatterns = [
    re_path(r'^index$', views.blog_index, name='blog_index'),
    re_path(r'^detail/(\d+)/$', views.blog_details, name='blog_details'),
    re_path(r'^type/(\d+)/$', views.blog_types, name='blog_types'),
    re_path(r'^date_of_blogs/(\d+)/(\d+)$', views.blog_dates, name='blog_dates'),
]

mkjwebsite/mkjwebsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^comment/', include('comment.urls', namespace='comment_module')),
    re_path(r'^likes/', include('likes.urls', namespace='likes_module')),
    re_path(r'^blogs/', include('blogs.urls', namespace='blogs_module')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^user/', include('user.urls', namespace='user')),
]

# 该方法是临时测试用的，部署之前需要替换掉 TODO
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkjwebsite/user/urls.py
from django.urls import re_path
from . import views

app_name = 'user'

urlpatterns = [
    re_path(r'^login_modal/$', views.login_modal, name='login_modal'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^user_info/$', views.user_info, name='user_info'),
    re_path(r'^change_nickname/$', views.change_nick_name, name='change_nickname'),
    re_path(r'^bind_email/$', views.bind_email, name='bind_email'),
    re_path(r'^send_email_code/$', views.send_email_code, name='send_email_code'),
    re_path(r'^change_password/$', views.change_password, name='change_password'),
    re_path(r'^forget_password/$', views.forget_password, name='forget_password'),
]

mkjwebsite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap-3.3-1.7-dist/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3-1.7-dist/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block cssstyle %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">个人博客网站</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% block home_active %}{% endblock %}"><a href="{% url 'home' %}">首页</a></li>
                <li class="{% block blog_active %}{% endblock %}"><a href="{% url 'blogs_module:blog_index' %}">博客</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">更多 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'home' %}">首页</a></li>
                        <li><a href="{% url 'blogs_module:blog_index' %}">博客</a></li>
                        <li><a href="{% url 'home' %}">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'home' %}">小游戏</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'home' %}">老司机</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登陆</a></li>
                    <li><a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a></li>
                {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            {% if user.has_nickname %}
                                {{ user.username }}({{ user.get_nickname }})
                            {% else %}
                                {{ user.username }}
                            {% endif %}

                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'user:user_info' %}">个人中心</a></li>
                            <li><a href="{% url 'user:change_password' %}">修改密码</a></li>
                            {% if user.is_staff or user.is_superuser %}
                                <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>
{% block content %}

{% endblock %}

<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="login_modal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form id="login_modal_form" action="" method="POST">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">登录</h4>
                </div>
                <div class="modal-body">

                    {% csrf_token %}
                    {#每个页面都要传，因此写个context_processors来默认携带，类似user和request#}
                    {% for field in login_modal_form %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    {% endfor %}
                    <span id="login_modal_tips" class="text-danger"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="submit" class="btn btn-primary">登录</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#login_modal_form').submit(function () {
        $('#login_modal_tips').text('')
        $.ajax({
            url: "{% url 'user:login_modal' %}",
            data: $(this).serialize(),
            type: 'POST',
            cache: false,
            success: function (data) {
                if (data['code'] == 200) {
                    $('#login_modal_tips').text('')
                    window.location.reload()
                } else {
                    $('#login_modal_tips').text('用户名或者密码不正确')
                }

            },
            error: function (xhr) {
                consolo.log(xhr)
            }
        });
        return false;
    })
</script>

{% block script_extend %}

{% endblock %}


</body>
</html>

mkjwebsite/templates/error.html
{% extends 'base.html' %}


{% block title %}
    个人博客错误网站
{% endblock %}


{% block blog_active %}
    active
{% endblock %}


{% block content %}
    {{ message }}
{% endblock %}

mkjwebsite/templates/form.html
{% extends 'base.html' %}

{% block title %}{{ page_title }}{% endblock %}
{% block home_active %}active{% endblock %}


{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ form_title }}</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                {#部分表单有隐藏字段 #}
                                {% if not field.is_hidden %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% endif %}
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span id="err_tips" class="text-danger">{{ form.non_field_errors }}</span>
                            <div class="clearfix"></div>
                            <div class="pull-left">
                                {% block other_buttons %}

                                {% endblock %}
                            </div>

                            <div class="pull-right">
                                <input type="submit" value="{{ submit_text }}" class="btn btn-primary pull-right">
                                <button class="btn btn-default" onclick="window.location.href='{{ retern_back_url }}'">
                                    返回
                                </button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mkjwebsite/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block title %}
    个人博客网站
{% endblock %}


{% block home_active %}
    active
{% endblock %}


{% block content %}
    <h1 class="content">欢迎来到{{ user.username }}的网站</h1>
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <div class="hot_blog">
        <h4>今日热门博客</h4>
        <ul>
            {% for read_detail in todays_hots %}
                <li><a href="{% url 'blogs_module:blog_details' read_detail.object_id %}">{{ read_detail.content_object.title }}({{ read_detail.read_num }})</a></li>
            {% empty %}
                暂无今日热门
            {% endfor %}

        </ul>
    </div>
    <div class="hot_blog">
        <h4>昨日热门博客</h4>
        <ul>
            {% for read_detail in yesterday_hots %}
                <li><a href="{% url 'blogs_module:blog_details' read_detail.object_id %}">{{ read_detail.content_object.title }}({{ read_detail.read_num }})</a></li>
            {% empty %}
                暂无今日热门
            {% endfor %}

        </ul>
    </div>
    <div class="hot_blog">
        <h4>过去7天热门博客</h4>
        <ul>
            {% for blog in seven_read_hots %}
                <li><a href="{% url 'blogs_module:blog_details' blog.id %}">{{ blog.title }}({{ blog.read_num_sum }})</a></li>
            {% empty %}
                暂无今日热门
            {% endfor %}

        </ul>
    </div>
    <script>
        // 图表配置
        var options = {
            chart: { type: 'line' },
            title: { text: null },
            xAxis: {
                categories: {{ dates|safe }},   // x 轴分类
                tickmarkPlacement: 'on',
            },
            yAxis: {
                title: { text: null },
                labels:{ enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                     // 数据列名
                data: {{ seven_read_counts }}               // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },
            credits: { enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}

mkjwebsite/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    个人博客登录
{% endblock %}

{% block cssstyle %}


{% endblock %}


{% block home_active %}
    active
{% endblock %}


{% block content %}
    {# 当前页面进行数据登录判断，跳转根据前面的from来 #}
    {# http://localhost:8000/login?from=/blogs/detail/41/ #}
    {#    <form action="" method="POST">#}
    {#        {% csrf_token %}#}
    {#        {{ loginform  }}#}
    {#        <input type="submit" value="登录">#}
    {#    </form>#}

    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in loginform %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                            <input type="submit" value="登录" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}