mkjwebsite/blogs/urls.py
from django.urls import path, re_path, reverse
from . import views

app_name = 'blogs'

urlpatterns = [
    re_path(r'^index$', views.blog_index, name='blog_index'),
    re_path(r'^detail/(\d+)/$', views.blog_details, name='blog_details'),
    re_path(r'^type/(\d+)/$', views.blog_types, name='blog_types'),
    re_path(r'^date_of_blogs/(\d+)/(\d+)$', views.blog_dates, name='blog_dates'),
]

mkjwebsite/mkjwebsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^comment/', include('comment.urls', namespace='comment_module')),
    re_path(r'^likes/', include('likes.urls', namespace='likes_module')),
    re_path(r'^blogs/', include('blogs.urls', namespace='blogs_module')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^user/', include('user.urls', namespace='user')),
]

# 该方法是临时测试用的，部署之前需要替换掉 TODO
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkjwebsite/user/urls.py
from django.urls import re_path
from . import views

app_name = 'user'

urlpatterns = [
    re_path(r'^login_modal/$', views.login_modal, name='login_modal'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^user_info/$', views.user_info, name='user_info'),
    re_path(r'^change_nickname/$', views.change_nick_name, name='change_nickname'),
    re_path(r'^bind_email/$', views.bind_email, name='bind_email'),
    re_path(r'^send_email_code/$', views.send_email_code, name='send_email_code'),
    re_path(r'^change_password/$', views.change_password, name='change_password'),
    re_path(r'^forget_password/$', views.forget_password, name='forget_password'),
]

mkjwebsite/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.contenttypes.models import ContentType
from read_statistics.models import ReadNumExtension, ReadNumDetail
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse


class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name


class Blog(models.Model,ReadNumExtension):
    title = models.CharField(max_length=50)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)
    readDetails = GenericRelation(ReadNumDetail)  # 反向关联获取


    def __str__(self):
        return "<Blog:%s>" % self.title

    def get_url(self):
        return reverse('blogs:blog_details', args=[self.pk])


    def get_email(self):
        return self.author.email

    # 添加作用分页，主要需要数据库迁移
    class Meta:
        ordering = ['-create_time']

mkjwebsite/blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog, BlogType
from django.core.paginator import Paginator
from django.db.models import Count
from django.conf import settings
from read_statistics.utils import read_statistics_by_every_read


def blog_datas_common(request, lists):
    paginator = Paginator(lists, settings.EACH_PAGE_NUMBERS)
    current_page_num = request.GET.get('page', '1')

    if not current_page_num.isdigit():
        print('非法数字')
        current_page_num = '1'
    if int(current_page_num) > paginator.num_pages:
        current_page_num = paginator.num_pages
    if int(current_page_num) < 1:
        current_page_num = '1'

    page_of_blogs = paginator.get_page(current_page_num)
    page_range = list(range(max(int(current_page_num) - 2, 1), int(current_page_num))) + \
                 list(range(int(current_page_num), min(int(current_page_num) + 2, paginator.num_pages) + 1))
    print(page_range)

    if page_range[0] - 1 >= 2:
        page_range.insert(0, '...')
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append('...')

    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    # 提取日期分类中的文章数 dict来存取
    blog_dates_tags = Blog.objects.dates('create_time', 'month', 'DESC')
    blog_dates_dict = {}
    for date in blog_dates_tags:
        blog_dates_dict[date] = Blog.objects.filter(create_time__year=date.year, create_time__month=date.month).count()

    context = {}
    context['page_of_blogs'] = page_of_blogs
    context['page_range'] = page_range
    context['blogTypes'] = BlogType.objects.annotate(type_count=Count('blog'))  # model直接挂一个字段type_count
    context['blogDates'] = blog_dates_dict
    return context


# Create your views here.
def blog_index(request):
    blogs = Blog.objects.all()
    context = blog_datas_common(request, blogs)
    return render(request, 'blogs/blog_index.html', context)


def blog_types(request, blog_type):
    blogType = get_object_or_404(BlogType, pk=blog_type)
    blogs = Blog.objects.filter(blog_type=blogType)
    context = blog_datas_common(request, blogs)
    context['blog_type'] = blogType
    return render(request, 'blogs/blog_type_list.html', context)


def blog_dates(request, year, month):
    blogs = Blog.objects.filter(create_time__year=year, create_time__month=month)
    context = blog_datas_common(request, blogs)
    context['blog_title_with_date'] = "%s年%s月" % (year, month)
    return render(request, 'blogs/blog_dates.html', context)


def blog_details(request, blog_pk):
    blog = get_object_or_404(Blog, pk=blog_pk)
    key = read_statistics_by_every_read(request, blog)
    pre_blog = Blog.objects.filter(create_time__gt=blog.create_time).last()
    next_blog = Blog.objects.filter(create_time__lt=blog.create_time).first()

    # ct =  ContentType.objects.get_for_model(blog)
    # comments =  Comment.objects.filter(content_type=ct, object_id=blog_pk, parent=None)

    # context['comments'] = comments.order_by('-comment_time')
    # context['comment_forms'] = CommentForm(initial={'content_type':ct.model,'object_id':blog.pk,'reply_comment_id':0})


    context = {}
    context['blog'] = blog
    context['previous_blog'] = pre_blog
    context['next_blog'] = next_blog
    response = render(request, 'blogs/blog_detail.html', context)
    response.set_cookie(key, True)
    return response

mkjwebsite/templates/blogs/blog_dates.html
{% extends 'blogs/blog_index.html' %}

{% block blog_title_header %}
    {{ blog_title_with_date }}
{% endblock %}

mkjwebsite/templates/blogs/blog_index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load comment_tags %}
{% load read_tags %}
{% load like_tags %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'blog_css/blog.css' %}">
{% endblock %}

{% block title %}
    我的网站
{% endblock %}

{% block blog_active %}
    active
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">{% block blog_title_header %}博客列表（一共有{{ page_of_blogs.paginator.count }}
                        篇博客）{% endblock %}</div>
                    <div class="panel-body">
                        <ul class="blog_types">
                            {% for blog in page_of_blogs.object_list %}
                                <div class="every_blog">
                                    <h3><a href="{% url 'blogs_module:blog_details' blog.pk %}">{{ blog.title }}</a>
                                    </h3>
                                    <ul class="blog_list_style">

                                        <li>
                                            <span class="glyphicon glyphicon-tags"></span> <a
                                                href="{% url 'blogs_module:blog_types' blog.blog_type.pk %}"> {{ blog.blog_type.type_name }}</a>
                                        </li>
                                        <li><span
                                                class="glyphicon glyphicon-time"></span> {{ blog.create_time|date:"Y-m-d" }}
                                        </li>
                                         <li>
                                             阅读:{% get_total_read_count blog %}
                                        </li>
                                        <li>
                                            评论:{% get_comment_count blog %}
                                        </li>
                                        <li>
                                            点赞:{% get_liked_counts blog %}
                                        </li>
                                    </ul>
                                    <p>{{ blog.content |striptags | truncatechars:130 |safe}}</p>
                                </div>

                            {% empty %}
                                <div class="every_blog">
                                    <p>--暂无博客，敬请期待--</p>
                                </div>

                            {% endfor %}

                        </ul>
                    </div>
                </div>
                <div class="blog_page_container">
                    {% if page_of_blogs %}
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                <li>
                                    {% if page_of_blogs.has_previous %}
                                        <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    {% else %}
                                        <span aria-hidden="true">&laquo;</span>
                                    {% endif %}

                                </li>
                                {% for page_num in page_range %}
                                    {% if page_num == '...' %}
                                        <li><span>{{ page_num }}</span></li>
                                    {% else %}
                                        {% if page_num == page_of_blogs.number %}
                                            <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                        {% else %}
                                            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                        {% endif %}
                                    {% endif %}

                                {% endfor %}
                                <li>
                                    {% if page_of_blogs.has_next %}
                                        <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    {% else %}
                                        <span aria-hidden="true">&raquo;</span>
                                    {% endif %}

                                </li>
                            </ul>
                        </nav>

                        <p>当前第{{ page_of_blogs.number }}篇（一共有{{ page_of_blogs.paginator.count }}
                            篇博客）</p>
                    {% endif %}


                </div>

            </div>
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
                <div class="panel panel-default">
                    <div class="panel-heading">博客分类</div>
                    <div class="panel-body">
                        <ul class="blog_types">
                            {% for type in blogTypes %}
                                <li><a href="{% url 'blogs:blog_types' type.pk %}">{{ type.type_name }} ({{ type.type_count }})</a></li>
                            {% empty %}
                                暂无博客分类
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">按时间归档</div>
                    <div class="panel-body">
                        <ul class="list-unstyled">
                            {% for blogDate,blogDateCount in blogDates.items %}
                                <li><a href="{% url 'blogs_module:blog_dates' blogDate.year blogDate.month %}">{{ blogDate|date:"Y年m月" }} ({{ blogDateCount }})</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

mkjwebsite/templates/blogs/blog_type_list.html
{% extends 'blogs/blog_index.html' %}

{% block title %}
    {{ blog_type.type_name }}
{% endblock %}

{% block blog_title_header %}
    博客分类：<a href="{% url 'blogs_module:blog_types' blog_type.pk %}">{{ blog_type.type_name }}</a>
{% endblock %}