mkjwebsite/mkjwebsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^comment/', include('comment.urls', namespace='comment_module')),
    re_path(r'^likes/', include('likes.urls', namespace='likes_module')),
    re_path(r'^blogs/', include('blogs.urls', namespace='blogs_module')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^user/', include('user.urls', namespace='user')),
]

# 该方法是临时测试用的，部署之前需要替换掉 TODO
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkjwebsite/user/urls.py
from django.urls import re_path
from . import views

app_name = 'user'

urlpatterns = [
    re_path(r'^login_modal/$', views.login_modal, name='login_modal'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^user_info/$', views.user_info, name='user_info'),
    re_path(r'^change_nickname/$', views.change_nick_name, name='change_nickname'),
    re_path(r'^bind_email/$', views.bind_email, name='bind_email'),
    re_path(r'^send_email_code/$', views.send_email_code, name='send_email_code'),
    re_path(r'^change_password/$', views.change_password, name='change_password'),
    re_path(r'^forget_password/$', views.forget_password, name='forget_password'),
]

mkjwebsite/user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from .models import Introduction


# forms.ModelForm 与 forms.Form
# 前者需要写入数据库，进行数据迁移  后者 如果提交表单后 不会对数据库就行修改，则继承Form类。
class LoginForm(forms.Form):
    username_or_email = forms.CharField(
        label='用户名或邮箱',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入用户名或邮箱'})
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'})
    )

    # hook isvalid方法后续的验证
    def clean(self):
        username_or_email = self.cleaned_data['username_or_email']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class RegisterForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        max_length=30,
        min_length=3,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入3-30位用户名'})
    )

    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱'})
    )

    verification_code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入验证码'}
        )
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'})
    )

    password_again = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '请再次输入密码'})
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断验证码
        code = self.request.session.get('register_send_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已被注册')
        return email

    def clean_verification_code(self):
        code = self.cleaned_data.get('verification_code', '').strip()
        if code == '':
            raise forms.ValidationError('验证码不能为空~')
        return code

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']

        if password != password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password_again


class NickNameForm(forms.Form):
    nickname_new = forms.CharField(
        label='新的昵称',
        max_length=15,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入新的昵称'})
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(NickNameForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户未登录')

    def clean_nickname_new(self):
        nickname = self.cleaned_data.get('nickname_new', '').strip()
        if nickname == '':
            raise forms.ValidationError('新的昵称不能为空')

        if Introduction.objects.filter(nick_name=nickname).exists():
            raise forms.ValidationError('昵称已被使用')
        return nickname


class BindEmailForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入正确的邮箱'}
        )
    )

    verification_code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入验证码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户未登录~')

        if self.request.user.email:
            raise forms.ValidationError('用户已绑定邮箱~')

        code = self.request.session.get('bind_email_send_code', '')
        input_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == input_code):
            raise forms.ValidationError('验证码不正确')

        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已被绑定~')
        return email

    def clean_verification_code(self):
        code = self.cleaned_data.get('verification_code', '').strip()
        if code == '':
            raise forms.ValidationError('验证码不能为空~')
        return code

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        label='旧的密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入旧的密码'})
    )
    new_password = forms.CharField(
        label='新的密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入新的密码'})
    )
    new_password_again = forms.CharField(
        label='再次输入密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请再次输入新的密码'})
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 新密码是否一致
        new_password = self.cleaned_data.get('new_password', '')
        new_password_again = self.cleaned_data.get('new_password_again', '')
        if new_password != new_password_again or new_password == '' or new_password_again == '':
            raise forms.ValidationError('两次密码不一致')
        return self.cleaned_data

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password', '')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('旧密码验证错误')
        return old_password



class ForgetPasswordForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入绑定过的邮箱'}
        )
    )

    verification_code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入验证码'}
        )
    )

    new_password = forms.CharField(
        label='新的的密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入新的密码'})
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgetPasswordForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email =  self.cleaned_data.get('email', '')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱下的用户不存在')
        return email


    def clean_verification_code(self):
        code = self.cleaned_data.get('verification_code', '').strip()
        if code == '':
            raise forms.ValidationError('验证码不能为空~')

        code = self.request.session.get('forget_password_send_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')

        return code

mkjwebsite/user/views.py
import re
import random
import string
import time
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.mail import send_mail
from .forms import LoginForm, RegisterForm, NickNameForm, BindEmailForm, ChangePasswordForm, ForgetPasswordForm
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from .models import Introduction


def ErrorResponse(code, message):
    res = {}
    res['code'] = '%s' % code
    res['message'] = message
    res['status'] = 'ERROR'
    return JsonResponse(res)


def SuccessResponse():
    res = {}
    res['status'] = 'SUCCESS'
    res['code'] = '200'
    return JsonResponse(res)


def login_modal(request):
    loginForm = LoginForm(request.POST)
    res = {}
    if loginForm.is_valid():
        user = loginForm.cleaned_data['user']
        auth.login(request, user)
        res['code'] = '200'
    else:
        res['code'] = '10008'
    return JsonResponse(res)


def login(request):
    if request.method == 'POST':
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            user = loginForm.cleaned_data['user']
            auth.login(request, user)
            return redirect(request.GET.get('from', reverse('home')))
    else:
        loginForm = LoginForm()
    context = {}
    context['loginform'] = loginForm
    return render(request, 'user/login.html', context)


def logout(request):
    auth.logout(request)
    return redirect(request.GET.get('from', reverse('home')))


def register(request):
    if request.method == 'POST':
        registerform = RegisterForm(request.POST, request=request)
        if registerform.is_valid():
            username = registerform.cleaned_data['username']
            email = registerform.cleaned_data['email']
            password = registerform.cleaned_data['password']

            user = User.objects.create_user(username, email, password)
            user.save()

            del request.session['register_send_code']

            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)

            return redirect(request.GET.get('from', reverse('home')))
    else:
        registerform = RegisterForm()
    context = {}
    context['registerform'] = registerform
    return render(request, 'user/register.html', context)


def user_info(request):
    return render(request, 'user/user_info.html', {})


def change_nick_name(request):
    redirect_to = request.GET.get('from', reverse('home'))
    if request.method == 'POST':
        form = NickNameForm(request.POST, user=request.user)
        if form.is_valid():
            nickname = form.cleaned_data['nickname_new']
            instroduction, created = Introduction.objects.get_or_create(user=request.user)
            instroduction.nick_name = nickname
            instroduction.save()
            return redirect(redirect_to)
    else:
        form = NickNameForm()

    context = {}
    context['page_title'] = '修改昵称'
    context['form_title'] = '修改昵称'
    context['submit_text'] = '提交'
    context['retern_back_url'] = redirect_to
    context['form'] = form
    return render(request, 'form.html', context)


def bind_email(request):
    redirect_to = request.GET.get('from', reverse('home'))
    if request.method == 'POST':
        form = BindEmailForm(request.POST, request=request)
        if form.is_valid():
            email = form.cleaned_data['email']
            request.user.email = email
            request.user.save()
            del request.session['bind_email_send_code']
            return redirect(redirect_to)
            # TODO 输入错误
            # return ErrorResponse('500', list(form.errors.values())[0][0])
    else:
        form = BindEmailForm()

    context = {}
    context['page_title'] = '绑定邮箱'
    context['form_title'] = '绑定邮箱'
    context['submit_text'] = '绑定'
    context['retern_back_url'] = redirect_to
    context['form'] = form
    return render(request, 'user/bind_email.html', context)


def send_email_code(request):
    email = request.GET.get('email', '')
    send_type = request.GET.get('send_type', '')
    if email == '':
        return ErrorResponse('10006', '绑定邮箱为空')
    if not re.match(r'^[0-9a-zA-Z_]{0,19}@[0-9a-zA-Z]{1,13}\.[com,cn,net]{1,3}$', email):
        return ErrorResponse('10007', '绑定邮箱格式验证失败')

    if send_type != 'forget_password_send_code':
        if User.objects.filter(email=email).exists():
            return ErrorResponse('10009', '邮箱已被绑定~')

    code = ''.join(random.sample(string.digits + string.ascii_letters, 4))

    now = int(time.time())
    send_time = request.session.get('send_code_time', 0)
    if now - send_time < 30:
        return ErrorResponse('10008', '验证码发送太频繁')
    else:
        request.session['send_code_time'] = now
        request.session[send_type] = code

        send_mail(
            '绑定邮箱',
            '验证码：%s' % code,
            '714831204@qq.com',
            [email],
            fail_silently=False,
        )
        return SuccessResponse()


def change_password(request):
    redirect_to = reverse('home')
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST, user=request.user)
        if form.is_valid():
            user = request.user
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            auth.logout(request)
            return redirect(redirect_to)
    else:
        form = ChangePasswordForm()

    context = {}
    context['page_title'] = '修改密码'
    context['form_title'] = '修改密码'
    context['submit_text'] = '修改'
    context['retern_back_url'] = redirect_to
    context['form'] = form
    return render(request, 'form.html', context)

def forget_password(request):
    redirect_to = reverse('user:login')
    if request.method == 'POST':
        form = ForgetPasswordForm(request.POST, request=request)
        if form.is_valid():
            # TODO 这里表单已经验证过了，因此直接拿肯定有值，比如【】，比如get不需要再判断
            new_password = form.cleaned_data['new_password']
            email =  form.cleaned_data['email']
            user = User.objects.get(email=email)
            user.set_password(new_password)
            user.save()
            del request.session['forget_password_send_code']
            return redirect(redirect_to)
    else:
        form = ForgetPasswordForm()

    context = {}
    context['page_title'] = '重置密码'
    context['form_title'] = '重置密码'
    context['submit_text'] = '重置'
    context['retern_back_url'] = redirect_to
    context['form'] = form
    return render(request, 'user/forget_password.html', context)

mkjwebsite/templates/user/bind_email.html
{% extends 'form.html' %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}


{% block script_extend %}r

    <script type="text/javascript">
        $('#send_code').click(function () {
            var email =  $('#id_email').val();
            if (email == ''){
                $('#err_tips').text('邮箱不能为空');
            }
            // 前端可以正则 TODO 优化错误是否倒计时
            $.ajax({
                url:"{% url 'user:send_email_code' %}",
                method: "GET",
                data:{
                    email:email
                },
                cache:false,
                success:function (data) {
                    if (data['code'] == 200){

                    } else {
                        alert(data['message'])
                    }
                }

            });
            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time --;
                $(this).text(time + 's');
            }, 1000);
            return false
        });
    </script>

{% endblock %}

mkjwebsite/templates/user/forget_password.html
{% extends 'form.html' %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}


{% block script_extend %}r

    <script type="text/javascript">
        $('#send_code').click(function () {
            var email =  $('#id_email').val();
            if (email == ''){
                $('#err_tips').text('邮箱不能为空');
            }
            // 前端可以正则 TODO 优化错误是否倒计时
            $.ajax({
                url:"{% url 'user:send_email_code' %}",
                method: "GET",
                data:{
                    email:email,
                    send_type:'forget_password_send_code',
                },
                cache:false,
                success:function (data) {
                    if (data['code'] == 200){

                    } else {
                        alert(data['message'])
                    }
                }

            });
            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time --;
                $(this).text(time + 's');
            }, 1000);
            return false
        });
    </script>

{% endblock %}

mkjwebsite/templates/user/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    个人博客登录
{% endblock %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'login.css' %}">

{% endblock %}


{% block home_active %}
    active
{% endblock %}


{% block content %}
    {# 当前页面进行数据登录判断，跳转根据前面的from来 #}
    {# http://localhost:8000/login?from=/blogs/detail/41/ #}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">登录</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in loginform %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger">{{ loginform.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <a class="pull-left" href="{% url 'user:forget_password' %}">忘记密码?</a>
                                <input type="submit" value="登录" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                {% else %}
                    <div style="text-align: center">
                        <div>已登录，跳转至首页...</div>
                        <img src="/media/loading.gif" alt="">
                    </div>
                    <script type="text/javascript">
                        setTimeout(function () {
                            window.location.href = '{% url 'home' %}';
                        }, 1000);

                    </script>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

mkjwebsite/templates/user/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    个人博客注册
{% endblock %}

{% block cssstyle %}
    <link rel="stylesheet" href="{% static 'login.css' %}">

{% endblock %}


{% block home_active %}
    active
{% endblock %}


{% block content %}
    {# 当前页面进行数据登录判断，跳转根据前面的from来 #}
    {# http://localhost:8000/login?from=/blogs/detail/41/ #}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in registerform %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger">{{ loginform.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <button id="send_code" class="btn btn-primary">发送验证码</button>
                                <input type="submit" value="注册" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                {% else %}
                    <div style="text-align: center">
                        <div>已登录，跳转至首页...</div>
                        <img src="/media/loading.gif" alt="">
                    </div>
                    <script type="text/javascript">
                        setTimeout(function () {
                            window.location.href = '{% url 'home' %}';
                        }, 1000);

                    </script>

                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block script_extend %}r

    <script type="text/javascript">
        $('#send_code').click(function () {
            var email =  $('#id_email').val();
            if (email == ''){
                $('#err_tips').text('邮箱不能为空');
            }
            // 前端可以正则 TODO 优化错误是否倒计时
            $.ajax({
                url:"{% url 'user:send_email_code' %}",
                method: "GET",
                data:{
                    email:email,
                    send_type:'register_send_code',
                },
                cache:false,
                success:function (data) {
                    if (data['code'] == 200){

                    } else {
                        alert(data['message'])
                    }
                }

            });
            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }
                time --;
                $(this).text(time + 's');
            }, 1000);
            return false
        });
    </script>

{% endblock %}

mkjwebsite/templates/user/user_info.html
{% extends 'base.html' %}


{% block title %}
    个人中心
{% endblock %}

{% block cssstyle %}

{% endblock %}


{% block home_active %}
    active
{% endblock %}


{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-8 col-xs-offset-1">
                {% if user.is_authenticated %}
                    <h3>{{ user.username }}</h3>
                    <ul>
                        <li>昵称：{{ user.get_nickname }} <a href="{% url 'user:change_nickname' %}?from={{ request.get_full_path }}">修改昵称</a></li>
                        <li>邮箱：{% if user.email %}{{ user.email }}{% else %}<a href="{% url 'user:bind_email' %}">绑定邮箱</a>{% endif %}</li>
                        <li>上次登录时间：{{ user.last_login|date:"Y-m-d H:i:s" }}</li>
                        <li><a href="{% url 'user:change_password' %}">修改密码</a></li>
                    </ul>
                {% else %}
                    <span>未登录，跳转至首页。。。</span>
                    <script type="text/javascript">
                        window.location.href = '{% url 'home' %}'
                    </script>
                {% endif %}


            </div>
        </div>
    </div>

{% endblock %}